language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'validator' ]; then cd .. && eval "mv $currentfolder validator" && cd validator; fi
after_script:
  - npm run coveralls

